package hrmanager.enums;

public enum Command {
	ADDEMPLOYEE, EDITEMPLOYEE, SHOWEMPLOYEES, DELETEEMPLOYEE, FINDEMPLOYEE,
	ADDDEPARTMENT, EDITDEPARTMENT, SHOWDEPARTMENTS, DELETEDEPARTMENT, FINDDEPARTMENT,
	EXIT
}
